"use strict";
exports.TableData = [
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
    {
        "eventId": "id1234",
        "date": "2017-03-16T15:23:04-05:00",
        "rawText": "HI HOW ARE YOU DOING TODAY",
        "processedText": "I AM DOING GOOD HW R U",
        "isTrdSearch": "F",
        "appCommand": "Search",
        "searchWord": "Show me",
        "deliverWord": "N/A",
        "contactWord": "N/A",
        "folderWord": "N/A",
        "folderName": "N/A",
        "queryText": "slip and fall",
        "citation": "N/A",
        "documentTitle": "N/A",
        "jurisdiction": "Minnesota",
        "contentType": "Cases",
        "isSuccessful": "T",
        "recordingLength": 5,
        "correlationId": "aksjdfkjsnfkjn",
        "sessionId": "fdhjkfsdgfsn",
        "sourceDevice": "ipad",
        "appVersion": 5.1,
        "operatingSystem": "10.3.2"
    },
];
